kind: pipeline
type: docker
name: cypress-examples

trigger:
  event:
    - pull_request

steps:
  - name: Run E2E Tests
    # image_pull: always
    image: cypress/included:13.16.1
    commands:
      - cypress run --reporter json --reporter-options "outputPath=cypress/results/results.json"

  - name: Post comment
    image: node:18
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
      commands:
        - node post-comment.js