kind: pipeline
type: docker
name: cypress-examples

# trigger:
#   event:
#     - pull_request
#     - commit

steps:
  # - name: Check Token
  #   image: alpine
  #   environment:
  #     GITHUB_TOKEN:
  #       from_secret: GITHUB_TOKEN
  #   commands:
  #     - echo "Token length:" $(echo -n "$GITHUB_TOKEN" | wc -c) # Calcula o comprimento do token
  #     - echo "Token starts with:" $(echo "$GITHUB_TOKEN" | cut -c1-4) # Exibe os 4 primeiros caracteres
  
  - name: Run E2E Tests
    # image_pull: always
    image: cypress/included:13.16.1
    commands:
      - cypress run --reporter json --reporter-options "outputPath=cypress/results/results.json"

  - name: Post comment
    image: node:18
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
      - cd cypress-examples/drone-pipeline-scripts
      - node post-comment.js